# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zitienne/Documents/Python/Nord VPN/QuickConnect/ui/maindlg.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        Dialog.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(8, 8, 545, 265))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.lwOptions = QtWidgets.QListWidget(self.widget)
        self.lwOptions.setMinimumSize(QtCore.QSize(0, 0))
        self.lwOptions.setObjectName("lwOptions")
        item = QtWidgets.QListWidgetItem()
        self.lwOptions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwOptions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwOptions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwOptions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwOptions.addItem(item)
        self.verticalLayout_11.addWidget(self.lwOptions)
        self.horizontalLayout.addWidget(self.widget)
        self.swSelection = QtWidgets.QStackedWidget(self.horizontalLayoutWidget)
        self.swSelection.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.swSelection.setFrameShadow(QtWidgets.QFrame.Plain)
        self.swSelection.setObjectName("swSelection")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pbConnectQuick = QtWidgets.QPushButton(self.page)
        self.pbConnectQuick.setWhatsThis("")
        self.pbConnectQuick.setObjectName("pbConnectQuick")
        self.gridLayout.addWidget(self.pbConnectQuick, 0, 0, 1, 1)
        self.pbDisconnectQuick = QtWidgets.QPushButton(self.page)
        self.pbDisconnectQuick.setObjectName("pbDisconnectQuick")
        self.gridLayout.addWidget(self.pbDisconnectQuick, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.swSelection.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.cbxCountry = QtWidgets.QComboBox(self.page_2)
        self.cbxCountry.setObjectName("cbxCountry")
        self.cbxCountry.addItem("")
        self.verticalLayout_2.addWidget(self.cbxCountry)
        self.cbxCity = QtWidgets.QComboBox(self.page_2)
        self.cbxCity.setObjectName("cbxCity")
        self.cbxCity.addItem("")
        self.verticalLayout_2.addWidget(self.cbxCity)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbConnectList = QtWidgets.QPushButton(self.page_2)
        self.pbConnectList.setEnabled(False)
        self.pbConnectList.setWhatsThis("")
        self.pbConnectList.setObjectName("pbConnectList")
        self.gridLayout_2.addWidget(self.pbConnectList, 0, 0, 1, 1)
        self.pbDisconnectList = QtWidgets.QPushButton(self.page_2)
        self.pbDisconnectList.setObjectName("pbDisconnectList")
        self.gridLayout_2.addWidget(self.pbDisconnectList, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 114, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.swSelection.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.cbxCode = QtWidgets.QComboBox(self.page_3)
        self.cbxCode.setEditable(True)
        self.cbxCode.setObjectName("cbxCode")
        self.cbxCode.addItem("")
        self.verticalLayout_3.addWidget(self.cbxCode)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.leCode = QtWidgets.QLineEdit(self.page_3)
        self.leCode.setObjectName("leCode")
        self.gridLayout_8.addWidget(self.leCode, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pbDisconnectCode = QtWidgets.QPushButton(self.page_3)
        self.pbDisconnectCode.setObjectName("pbDisconnectCode")
        self.gridLayout_3.addWidget(self.pbDisconnectCode, 1, 1, 1, 1)
        self.pbConnectCode = QtWidgets.QPushButton(self.page_3)
        self.pbConnectCode.setWhatsThis("")
        self.pbConnectCode.setObjectName("pbConnectCode")
        self.gridLayout_3.addWidget(self.pbConnectCode, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 145, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.swSelection.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pbStatusCheck = QtWidgets.QPushButton(self.page_4)
        self.pbStatusCheck.setMinimumSize(QtCore.QSize(100, 0))
        self.pbStatusCheck.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pbStatusCheck.setWhatsThis("")
        self.pbStatusCheck.setObjectName("pbStatusCheck")
        self.gridLayout_4.addWidget(self.pbStatusCheck, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_4.addWidget(self.textEdit_2)
        self.swSelection.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit = QtWidgets.QTextEdit(self.page_5)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.swSelection.addWidget(self.page_5)
        self.horizontalLayout.addWidget(self.swSelection)
        self.pteLog = QtWidgets.QPlainTextEdit(Dialog)
        self.pteLog.setGeometry(QtCore.QRect(8, 320, 545, 233))
        self.pteLog.setObjectName("pteLog")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(296, 280, 245, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pbClose = QtWidgets.QPushButton(self.layoutWidget)
        self.pbClose.setObjectName("pbClose")
        self.gridLayout_5.addWidget(self.pbClose, 0, 0, 1, 1)
        self.pbDisconnectAndClose = QtWidgets.QPushButton(self.layoutWidget)
        self.pbDisconnectAndClose.setObjectName("pbDisconnectAndClose")
        self.gridLayout_5.addWidget(self.pbDisconnectAndClose, 0, 1, 1, 1)
        self.cbViewTerminal = QtWidgets.QCheckBox(Dialog)
        self.cbViewTerminal.setGeometry(QtCore.QRect(24, 285, 209, 22))
        self.cbViewTerminal.setObjectName("cbViewTerminal")

        self.retranslateUi(Dialog)
        self.swSelection.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "NordVPN Quick Connect"))
        self.label.setText(_translate("Dialog", "CONNECT OPTIONS"))
        __sortingEnabled = self.lwOptions.isSortingEnabled()
        self.lwOptions.setSortingEnabled(False)
        item = self.lwOptions.item(0)
        item.setText(_translate("Dialog", "Quick Connect"))
        item = self.lwOptions.item(1)
        item.setText(_translate("Dialog", "Connect From List"))
        item = self.lwOptions.item(2)
        item.setText(_translate("Dialog", "Connect by Server Code"))
        item = self.lwOptions.item(3)
        item.setText(_translate("Dialog", "Check Status"))
        item = self.lwOptions.item(4)
        item.setText(_translate("Dialog", "About"))
        self.lwOptions.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("Dialog", "QUICK CONNECT"))
        self.pbConnectQuick.setToolTip(_translate("Dialog", "Connects to optimal VPN server"))
        self.pbConnectQuick.setText(_translate("Dialog", "Connect"))
        self.pbDisconnectQuick.setToolTip(_translate("Dialog", "Disconnects from server"))
        self.pbDisconnectQuick.setText(_translate("Dialog", "Disconnect"))
        self.label_3.setText(_translate("Dialog", "SELECT FROM LIST"))
        self.cbxCountry.setItemText(0, _translate("Dialog", "Select Country"))
        self.cbxCity.setItemText(0, _translate("Dialog", "Select City"))
        self.pbConnectList.setToolTip(_translate("Dialog", "Connects to optimal VPN server"))
        self.pbConnectList.setText(_translate("Dialog", "Connect"))
        self.pbDisconnectList.setToolTip(_translate("Dialog", "Disconnects from server"))
        self.pbDisconnectList.setText(_translate("Dialog", "Disconnect"))
        self.label_2.setText(_translate("Dialog", "SELECT BY SERVER"))
        self.cbxCode.setItemText(0, _translate("Dialog", "Select Code"))
        self.label_9.setText(_translate("Dialog", "Enter Code: "))
        self.pbDisconnectCode.setToolTip(_translate("Dialog", "Disconnects from server"))
        self.pbDisconnectCode.setText(_translate("Dialog", "Disconnect"))
        self.pbConnectCode.setToolTip(_translate("Dialog", "Connects to optimal VPN server"))
        self.pbConnectCode.setText(_translate("Dialog", "Connect"))
        self.label_5.setText(_translate("Dialog", "STATUS"))
        self.pbStatusCheck.setToolTip(_translate("Dialog", "Connects to optimal VPN server"))
        self.pbStatusCheck.setText(_translate("Dialog", "Check"))
        self.label_6.setText(_translate("Dialog", "ABOUT"))
        self.pbClose.setText(_translate("Dialog", "Close"))
        self.pbDisconnectAndClose.setText(_translate("Dialog", "DIsconnect && Close"))
        self.cbViewTerminal.setText(_translate("Dialog", "View Terminal Response"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
